app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'jobs#index'

  resources :nodes, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :job_types, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :plugins, only: [:show]

  post 'job_types/:job_type_id/step_types' => 'step_types#create'
  put 'job_types/:job_type_id/step_types/:step_type_id' => 'step_types#update'
  delete 'job_types/:job_type_id/step_types/:step_type_id' => 'step_types#destroy'

  namespace :node_api do
    post 'node' => 'node#register'
    post 'job' => 'job#update'
    post 'step' => 'step#update'
    post 'step/log' => 'step#submit_log'
  end

end

app/app/controllers/job_types_controller.rb
class JobTypesController < ApplicationController

  before_action :authenticate_user!, :fetch_summary_items

  def index
    @job_types = []
  end

  def new
    @job_type = JobType.new
  end

  def create
    name = params[:name]
    job_type = JobType.new({name: name, slug: name.dup.parameterize})

    unless job_type.save
      render status: 400, json: {}
      return
    end

    render status: 201, json: job_type.payload()
  end

  def update
    job_type = JobType.find(params[:id])

    if job_type.nil?
      render status: 404, json: {}
      return
    end

    params[:slug] = params[:name].dup.parameterize
    job_type.update_attributes(job_type_params)

    unless job_type.save
      render status: 400, json: {}
    end

    render status: 200, json: job_type.payload()
  end

  def show
    @job_type = JobType.find(params[:id])

    if request.content_type =~ /json/
      render status: 404, json: {} if @job_type.nil?
      render status: 200, json: @job_type.payload()
      return
    end

    render 'new'
  end

  private

  def job_type_params
    return params.require(:job_type).permit(:name, :slug)
  end

end

app/app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/app/views/job_types/_empty.html.erb
<div class="jumbotron">
  <h2><%= t('job_types.jumbo.title') %></h2>
  <br>
  <p><%= raw(t('job_types.jumbo.message')) %></p>
  <br>
  <p><%= link_to t('job_types.jumbo.button'), new_job_type_path, class: 'btn btn-success btn-lg', role: 'button'  %></p>
</div>

app/app/views/job_types/index.html.erb
<!-- Bradcrumb -->
<% content_for :breadcrumb_tabs do %>
  <li class="active"><%= t('job_types.breadcrumb.index') %></li>
  <%= link_to raw("<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span> #{t('job_types.breadcrumb.new')}"), new_job_type_path, class: 'btn btn-success btn-xs pull-right', role: 'button'  %>
<% end %>
<%= render 'breadcrumb' %>

<!-- Content -->
<%= render 'empty' if @job_types.empty? %>
<% unless @job_types.empty? %>
  <table class="table table-hover">
    <% @job_types.each do |job_type| %>
      <tr>
        <td class="row-node" data-node-id="<%= job_type.id %>">
          
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/app/views/job_types/new.html.erb
<!-- Breadcrumb -->
<% content_for :breadcrumb_tabs do %>
  <li><%= link_to t('job_types.breadcrumb.index'), job_types_path %></li>
  <li class="active">
    <%= t('job_types.breadcrumb.new') if action_name == 'new' %>
    <%= @job_type.name if action_name == 'show' %>
  </li>
<% end %>
<%= render 'breadcrumb' %>
<%= react_component('JobTypeForm', id: @job_type.id, editable: true) %>

<!--
<button type="button" class="btn btn-default btn-block">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add step
</button>
-->