app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'jobs#index'

  resources :nodes, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :job_types, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :plugins, only: [:show]

  post 'job_types/:job_type_id/step_types' => 'step_types#create'
  put 'job_types/:job_type_id/step_types/:step_type_id' => 'step_types#update'
  delete 'job_types/:job_type_id/step_types/:step_type_id' => 'step_types#destroy'

  namespace :node_api do
    post 'node' => 'node#register'
    post 'job' => 'job#update'
    post 'step' => 'step#update'
    post 'step/log' => 'step#submit_log'
  end

end

app/app/models/node.rb
class Node < ActiveRecord::Base

  validates :alias, length: { minimum: 4 }

  enum status: [ :unpaired, :offline, :online ]

end

app/app/controllers/node_api/node_controller.rb
class NodeApi::NodeController < ApplicationController

  skip_before_filter  :verify_authenticity_token

  def register
    token = request.headers['X-Joaquin-Node-Token']
    puts request.headers
    nodes = Node.where(token: token )
    node = nodes.first unless nodes.empty?
    node.update_attributes(register_node_params) unless node.nil?
    if !node.nil? && node.save
      node.update_attributes({
        status: :online,
        last_active: Time.now
      })
      node.save
      render status: 201, json: {}
    else
      errors = node.errors.full_messages unless node.nil?
      render status: 404, json: { error_messages: errors }
    end
  end

  def register_node_params
    return params.require(:node).permit(:os, :arch, :system, :local_host, :ip_address, :port, :shell, :user, :home_dir)
  end

end

app/app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  before_action :authenticate_user!, :fetch_summary_items

  def index
    @nodes = Node.all
  end

  def create
    # Create and persist node instance
    node = Node.new(node_params)

    if node.save
      flash[:notice] = I18n.t('nodes.form.success_message_create', node_name: node.alias)
      redirect_to action: 'index'
    else
      flash[:error] = node.errors.full_messages.join('. ')
      redirect_to action: 'new', alias: node.alias
    end
  end

  def new
    @node = Node.new({ alias: params[:alias], token: generate_hash })
    @target_action = 'create'
  end

  def show
    @node = Node.find(params[:id])
    @target_action = 'update'
    render 'new'
  end

  def update
    node = Node.find(params[:id])
    node.update_attributes(node_params)
    if node.save
      flash[:notice] = I18n.t('nodes.form.success_message_update', node_name: node.alias)
      redirect_to action: 'index'
    else
      flash[:error] = node.errors.full_messages.join('. ')
      redirect_to action: 'show', id: node.id
    end
  end

  def destroy
    node = Node.find(params[:id])
    if node.destroy
      flash[:notice] = I18n.t('nodes.form.success_message_delete', node_name: node.alias)
      redirect_to action: 'index'
    else
      flash[:error] = node.errors.full_messages.join('. ')
      redirect_to action: 'show', id: node.id
    end
  end

  private

  def node_params
    return params.require(:node).permit(:alias, :token)
  end

  def generate_hash
    chars = [('a'..'z'), ('A'..'Z'), ('<'..'@')].map(&:to_a).flatten
    return (0...32).map { chars[rand(chars.length)] }.join
  end

end

app/app/helpers/node_api/node_helper.rb
module NodeApi::NodeHelper
end

app/app/helpers/nodes_helper.rb
module NodesHelper
end

app/app/views/nodes/_details.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t('nodes.form.details') %></h3>
  </div>
  <div class="panel-body row">
    <div class="col-md-4">
      <div class="form-group">
        <label><%= t('nodes.form.system') %></label>
        <p class="form-control-static"><%= @node.system || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.os') %></label>
        <p class="form-control-static"><%= @node.os || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.arch') %></label>
        <p class="form-control-static"><%= @node.arch || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.shell') %></label>
        <p class="form-control-static"><%= @node.shell || 'N/A'  %></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label><%= t('nodes.form.user') %></label>
        <p class="form-control-static"><%= @node.user || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.home_dir') %></label>
        <p class="form-control-static"><%= @node.home_dir || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.local_host') %></label>
        <p class="form-control-static"><%= @node.local_host || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.public_host') %></label>
        <p class="form-control-static"><%= @node.public_host || 'N/A'  %></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label><%= t('nodes.form.ip_address') %></label>
        <p class="form-control-static"><%= @node.ip_address || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.port') %></label>
        <p class="form-control-static"><%= @node.port || 'N/A'  %></p>
      </div>
      <div class="form-group">
        <label><%= t('nodes.form.last_active') %></label>
        <p class="form-control-static"><%= @node.last_active || 'N/A'  %></p>
      </div>
    </div>
  </div>
</div>

app/app/views/nodes/_empty.html.erb
<div class="jumbotron">
  <h2><%= t('nodes.jumbo.title') %></h2>
  <br>
  <p><%= raw(t('nodes.jumbo.message')) %></p>
  <br>
  <p><%= link_to t('nodes.jumbo.button'), new_node_path, class: 'btn btn-success btn-lg', role: 'button'  %></p>
</div>

app/app/views/nodes/_form.html.erb
<%= form_for(@node, url: { action: @target_action }) do |f| %>
  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
          <%= f.label t('nodes.form.alias') %>
          <%= f.text_field :alias, class: 'form-control' %>
          <p class="help-block"><%= t('nodes.form.alias_desc') %></p>
        </div>
        <div class="form-group">
          <%= f.label t('nodes.form.token') %>
          <%= f.text_field :token, class: 'form-control', readonly: true %>
          <p class="help-block"><%= t('nodes.form.token_desc') %></p>
        </div>
        <% if @target_action == 'update' %>
          <button type="submit" class="btn btn-warning btn-block"><%= t('nodes.form.submit_update') %></button>
          <p></p>
          <%= link_to t('nodes.form.submit_delete'), node_path(@node.id), method: 'delete', class: 'btn btn-danger btn-block' %>
        <% else %>
          <button type="submit" class="btn btn-success btn-block"><%= t('nodes.form.submit_create') %></button>
        <% end %>
        <br>
    </div>
    <div class="col-md-6">
      <%= render 'help' %>
    </div>
  </div>
<% end %>

app/app/views/nodes/_help.html.erb
<label><%= t('nodes.help.title') %></label><br>
<body><%= raw(t('nodes.help.message')) %></body>
<p><pre>$> joaquin node run --help</pre></p>
<br>

app/app/views/nodes/_summary.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><strong><%= t('nodes.summary.title') %></strong></div>
  <div class="panel-body">
    <% if @active_nodes.empty? %>
      <span class="label label-danger"><%= t('nodes.summary.placeholder') %></span>
    <% else %>
      Panel content
    <% end %>
  </div>
</div>

app/app/views/nodes/index.html.erb
<!-- Bradcrumb -->
<% content_for :breadcrumb_tabs do %>
  <li class="active"><%= t('nodes.breadcrumb.index') %></li>
  <%= link_to raw("<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span> #{t('nodes.breadcrumb.new')}"), new_node_path, class: 'btn btn-success btn-xs pull-right', role: 'button'  %>
<% end %>
<%= render 'breadcrumb' %>

<!-- Content -->
<%= render 'empty' if @nodes.empty? %>
<% unless @nodes.empty? %>
  <table class="table table-hover">
    <% @nodes.each do |node| %>
      <tr>
        <td class="row-node" data-node-id="<%= node.id %>">
          <p>
            <label><%= node.alias %></label>
            <% if node.status == 'unpaired' %>
            <span class="label label-warning">never paired</span>
            <% elsif node.status == 'online' %>
            <%= "#{node.os}-#{node.system}-#{node.arch}" %>
            <span class="label label-success">online</span>
            <% end %>
          </p>
          Token <code><%= node.token %></code>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/app/views/nodes/new.html.erb
<!-- Bradcrumb -->
<% content_for :breadcrumb_tabs do %>
  <li><%= link_to t('nodes.breadcrumb.index'), nodes_path %></li>
  <li class="active">
    <%= t('nodes.breadcrumb.new') if action_name == 'new' %>
    <%= @node.alias if action_name == 'show' %>
  </li>
<% end %>
<%= render 'breadcrumb' %>

<!-- Content -->
<%= render 'form' %>
<%= render 'details' if @node.status != 'unpaired' %>