app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'jobs#index'

  resources :nodes, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :job_types, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  resources :plugins, only: [:show]

  post 'job_types/:job_type_id/step_types' => 'step_types#create'
  put 'job_types/:job_type_id/step_types/:step_type_id' => 'step_types#update'
  delete 'job_types/:job_type_id/step_types/:step_type_id' => 'step_types#destroy'

  namespace :node_api do
    post 'node' => 'node#register'
    post 'job' => 'job#update'
    post 'step' => 'step#update'
    post 'step/log' => 'step#submit_log'
  end

end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def fetch_summary_items
    @active_nodes = Node.where(status: 'online')
    @jobs = []
  end

end

app/app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_type.to_s
    end
  end

end

app/app/views/application/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li><%= link_to t('breadcrumb.home'), root_path %></li>
  <%= yield :breadcrumb_tabs %>
</ol>

app/app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>

app/app/views/application/_navigation_bar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
      <a class="navbar-brand" href="#">Joaquin</a>
      <% end %>
    </div>
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> <%= t('navbar.tab_manage') %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('navbar.tab_jobs'), job_types_path %></li>
            <li><%= link_to t('navbar.tab_nodes'), nodes_path %></li>
            <li><a href="#"><%= t('navbar.tab_members') %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><%= t('navbar.tab_settings') %></a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= current_user.email  %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= t('navbar.tab_account') %></a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to(t('navbar.tab_logout'), destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
</nav>